"""Turn an imported Mesh into C the console can draw.

The layout is chosen for how the runtime reads it rather than for how it looks
in a file. Positions, texture coordinates and normals go into three flat
arrays, and triangles are indices into them, because the renderer transforms
each vertex exactly once and then walks the index list. A model with 2754
vertices and 3341 triangles has 10023 corners: transforming per corner instead
of per vertex is three times the work on a processor that has none to spare.

Parts are runs of that index list sharing one material, kept in order, because
every part is a texture bind and a bind costs a packet.
"""

import os

import numpy as np

from . import ps2budget


def _floats(values, per_line=6):
    out = []
    flat = np.asarray(values, dtype=np.float32).reshape(-1)
    for start in range(0, len(flat), per_line):
        chunk = flat[start:start + per_line]
        out.append('    ' + ','.join('%.6ff' % v for v in chunk) + ',')
    return out


def _ints(values, per_line=12):
    out = []
    flat = np.asarray(values).reshape(-1)
    for start in range(0, len(flat), per_line):
        chunk = flat[start:start + per_line]
        out.append('    ' + ','.join(str(int(v)) for v in chunk) + ',')
    return out


def compile_mesh(mesh, name, out_path, material_of=None):
    """Write `name` as a C header the runtime can include.

    `material_of` maps a part's material name to the index of a compiled
    material, so geometry and textures stay independent of each other -- the
    same mesh can be drawn with whatever the project happens to have loaded.
    """
    material_of = material_of or {}
    if len(mesh.positions) > 65535:
        raise ValueError('%s has %d vertices; the index type tops out at 65535'
                         % (name, len(mesh.positions)))

    lines = ['/* Generated by ncc from %s -- do not edit. */'
             % os.path.basename(str(mesh.source)),
             '#pragma once', '',
             'typedef struct { unsigned short first, count; short material; } NCMeshPart;',
             'typedef struct {',
             '    const float *pos, *uv, *nrm;',
             '    const unsigned short *index;',
             '    const NCMeshPart *parts;',
             '    int vertices, indices, parts_count;',
             '} NCMeshData;', '',
             '#define %s_VERTS %d' % (name.upper(), len(mesh.positions)),
             '#define %s_TRIS %d' % (name.upper(), mesh.triangle_count),
             '#define %s_PARTS %d' % (name.upper(), len(mesh.parts)), '']

    lines.append('static const float %s_pos[] = {' % name)
    lines += _floats(mesh.positions)
    lines.append('};')
    lines.append('static const float %s_uv[] = {' % name)
    lines += _floats(mesh.uvs)
    lines.append('};')
    lines.append('static const float %s_nrm[] = {' % name)
    lines += _floats(mesh.normals)
    lines.append('};')
    lines.append('static const unsigned short %s_index[] = {' % name)
    lines += _ints(mesh.indices)
    lines.append('};')

    lines.append('static const NCMeshPart %s_parts[] = {' % name)
    for part in mesh.parts:
        lines.append('    {%d, %d, %d},'
                     % (part.first, part.count,
                        material_of.get(part.material, 0)))
    lines.append('};')
    lines += ['', 'static const NCMeshData %s = {' % name,
              '    %s_pos, %s_uv, %s_nrm, %s_index, %s_parts,'
              % (name, name, name, name, name),
              '    %d, %d, %d' % (len(mesh.positions), len(mesh.indices),
                                  len(mesh.parts)),
              '};', '']

    with open(out_path, 'w', encoding='utf-8') as handle:
        handle.write('\n'.join(lines))

    bytes_used = (len(mesh.positions) * 8 * 4) + (len(mesh.indices) * 2)
    return {'vertices': len(mesh.positions), 'triangles': mesh.triangle_count,
            'parts': len(mesh.parts), 'bytes': bytes_used}


def report(stats, name):
    return ('  %s: %d triangles, %d vertices, %d part(s), %d KB in main memory'
            % (name, stats['triangles'], stats['vertices'], stats['parts'],
               stats['bytes'] // 1024))
