"""Turn a PNG into a C array the PS2 can upload straight to the GS.

The PS1 side packs textures into a .ncpkg because its runtime loads data at run
time. The PS2 side has no runtime yet -- a PS2 project is a hand-written main.c
-- so the honest thing today is to compile the pixels in, exactly as PS2SDK's
own samples do with their flower texture.

Format is GS_PSM_32: one 32-bit word per texel, RGBA in memory order. The alpha
convention is the one that trips everybody once -- **0x80 is fully opaque on
this hardware**, not 0xFF. 0xFF is over-bright and used for additive tricks.
Anything at 0x00 is what the alpha test rejects, which is how a cut-out logo
gets a transparent background without blending.

    python tools/png2ps2.py logo.png logo_data.c nc_logo 128

The size argument is optional and rescales; GS texture dimensions have to be
powers of two, so this refuses anything else rather than letting the console
sample garbage.
"""

import os
import sys

ALPHA_OPAQUE = 0x80
ALPHA_CUTOFF = 128          # source alpha below this becomes fully transparent


def is_pow2(n):
    return n > 0 and (n & (n - 1)) == 0


def next_pow2(n):
    p = 1
    while p < n:
        p *= 2
    return p


def convert(png, name, size=None):
    """Fit a PNG onto a power-of-two canvas and return its texels and metrics.

    GS texture dimensions have to be powers of two -- the hardware addresses
    them by shift rather than by multiply -- and almost no artwork is. Stretching
    an image to fit is what makes a wide logo look squashed, so instead it is
    scaled to fit inside the next power of two on each axis, padded with
    transparency, and the *used* area is reported alongside. The drawing code
    then samples only that region and draws it at its own aspect ratio.
    """
    from PIL import Image

    img = Image.open(png).convert("RGBA")
    if size:
        # Fit inside a size x size box, keeping the aspect ratio.
        img.thumbnail((size, size), Image.LANCZOS)

    used_w, used_h = img.size
    w, h = next_pow2(used_w), next_pow2(used_h)

    if (w, h) != (used_w, used_h):
        canvas = Image.new("RGBA", (w, h), (0, 0, 0, 0))
        canvas.paste(img, (0, 0))
        img = canvas

    words = []
    for r, g, b, a in img.getdata():
        if a < ALPHA_CUTOFF:
            # Fully transparent, and the colour is thrown away with it: a
            # transparent pixel that keeps its RGB bleeds a halo when the
            # hardware filters, and nearest sampling still shows it at edges.
            words.append(0)
        else:
            words.append((ALPHA_OPAQUE << 24) | (b << 16) | (g << 8) | r)

    return words, w, h, used_w, used_h


def emit(words, w, h, used_w, used_h, name, out, source):
    lines = []
    lines.append("/* Generated by tools/png2ps2.py from %s -- do not edit. */"
                 % os.path.basename(source))
    lines.append("")
    lines.append("#include <tamtypes.h>")
    lines.append("")
    lines.append("/* %dx%d, GS_PSM_32. Alpha is 0x80 for opaque and 0 for the"
                 % (w, h))
    lines.append(" * cut-out, which is what the alpha test keys on. */")
    lines.append("const int %s_width = %d;" % (name, w))
    lines.append("const int %s_height = %d;" % (name, h))
    lines.append("")
    lines.append("/* The part of the canvas the image occupies. Sampling the whole")
    lines.append(" * texture would include the transparent padding, and drawing a wide")
    lines.append(" * image as a square would squash it. */")
    lines.append("const int %s_used_w = %d;" % (name, used_w))
    lines.append("const int %s_used_h = %d;" % (name, used_h))
    lines.append("unsigned int %s[%d] __attribute__((aligned(16))) = {"
                 % (name, len(words)))

    for i in range(0, len(words), 8):
        row = ", ".join("0x%08X" % v for v in words[i:i + 8])
        lines.append("    %s," % row)
    lines.append("};")
    lines.append("")

    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    return len(words)


def main(argv):
    if len(argv) < 4:
        print(__doc__)
        return 2
    png, out, name = argv[1], argv[2], argv[3]
    size = int(argv[4]) if len(argv) > 4 else None
    words, w, h, uw, uh = convert(png, name, size)
    n = emit(words, w, h, uw, uh, name, out, png)
    print("Wrote %s  (%s, %dx%d canvas, %dx%d used, %d KB in the executable)"
          % (out, name, w, h, uw, uh, n * 4 // 1024))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
