"""Turn a PNG into a C array the PS2 can upload straight to the GS.

The PS1 side packs textures into a .ncpkg because its runtime loads data at run
time. The PS2 side has no runtime yet -- a PS2 project is a hand-written main.c
-- so the honest thing today is to compile the pixels in, exactly as PS2SDK's
own samples do with their flower texture.

Format is GS_PSM_32: one 32-bit word per texel, RGBA in memory order. The alpha
convention is the one that trips everybody once -- **0x80 is fully opaque on
this hardware**, not 0xFF. 0xFF is over-bright and used for additive tricks.
Anything at 0x00 is what the alpha test rejects, which is how a cut-out logo
gets a transparent background without blending.

    python tools/png2ps2.py logo.png logo_data.c nc_logo 128

The size argument is optional and rescales; GS texture dimensions have to be
powers of two, so this refuses anything else rather than letting the console
sample garbage.
"""

import os
import sys

ALPHA_OPAQUE = 0x80
ALPHA_CUTOFF = 128          # source alpha below this becomes fully transparent


def is_pow2(n):
    return n > 0 and (n & (n - 1)) == 0


def convert(png, name, size=None):
    from PIL import Image

    img = Image.open(png).convert("RGBA")
    if size:
        img = img.resize((size, size), Image.LANCZOS)
    w, h = img.size

    if not (is_pow2(w) and is_pow2(h)):
        raise SystemExit(
            "png2ps2: %s is %dx%d. GS texture dimensions have to be powers of "
            "two -- \n            the hardware addresses them by shift, not by "
            "multiply." % (os.path.basename(png), w, h))

    words = []
    for r, g, b, a in img.getdata():
        if a < ALPHA_CUTOFF:
            # Fully transparent, and the colour is thrown away with it: a
            # transparent pixel that keeps its RGB bleeds a halo when the
            # hardware filters, and nearest sampling still shows it at edges.
            words.append(0)
        else:
            words.append((ALPHA_OPAQUE << 24) | (b << 16) | (g << 8) | r)

    return words, w, h


def emit(words, w, h, name, out, source):
    lines = []
    lines.append("/* Generated by tools/png2ps2.py from %s -- do not edit. */"
                 % os.path.basename(source))
    lines.append("")
    lines.append("#include <tamtypes.h>")
    lines.append("")
    lines.append("/* %dx%d, GS_PSM_32. Alpha is 0x80 for opaque and 0 for the"
                 % (w, h))
    lines.append(" * cut-out, which is what the alpha test keys on. */")
    lines.append("const int %s_width = %d;" % (name, w))
    lines.append("const int %s_height = %d;" % (name, h))
    lines.append("unsigned int %s[%d] __attribute__((aligned(16))) = {"
                 % (name, len(words)))

    for i in range(0, len(words), 8):
        row = ", ".join("0x%08X" % v for v in words[i:i + 8])
        lines.append("    %s," % row)
    lines.append("};")
    lines.append("")

    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    return len(words)


def main(argv):
    if len(argv) < 4:
        print(__doc__)
        return 2
    png, out, name = argv[1], argv[2], argv[3]
    size = int(argv[4]) if len(argv) > 4 else None
    words, w, h = convert(png, name, size)
    n = emit(words, w, h, name, out, png)
    print("Wrote %s  (%s, %dx%d, %d texels, %d KB in the executable)"
          % (out, name, w, h, n, n * 4 // 1024))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
